### ISSUE TITLE
Pending tests

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#69]
This issue is to track areas of the library that have tests pending.

- [x] Perform necessary refactoring for tests: #62
- [x] Round trip test for TChannel: #63
- [x] HTTP unit tests: #64
- [x] transport.Header tests: #66
- [x] TChannel unit tests: #70
- [x] Add crossdock behaviors to regular test suite (#33): #91

**Comment by abhinav** [comment]
All done
