### ISSUE TITLE
gRPC Tracking Issue

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#903]
- [x] #904 oneway context propagation
- [x] #905 encoding application errors
- [ ] #906 standardize wire protocol for metadata
- [ ] #908 standardize convention for mapping procedure to gRPC path
- [ ] #909 support peer chooser
- [ ] #911 allow overriding grpc encoding headers  
- [x] #917 better understand and handle the grpc.ClientConn object
- [ ] #934 Add crossdock tests for google grpc implementations
- [x] #1015 Implement transport.Transport

Nice to haves:

- [ ] #912 add benchmarks
- [x] #920 Use existing grpc-go interfaces?
